/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: usernammee (https://sketchfab.com/usernammee)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/super-mario-odyssey-mario-3e0432d1a2574b4faed6db712e027619
title: Super Mario Odyssey - Mario
*/

import React, { useRef, useMemo, useCallback, useEffect } from "react";
import { Gltf, useGLTF } from "@react-three/drei";
import CannonUtils from "../lib/cannon";
import { useBox } from "@react-three/cannon";

useGLTF.preload("/mario.glb");

export function Mario(props) {
  const { materials, scene, nodes } = useGLTF("/mario_obj/scene.gltf");
  //   const args = useMemo(() => {
  //     const [vertice, indices] = CannonUtils.toTrimeshProps(
  //       nodes.Object_6.geometry
  //     );

  //     return [vertice, indices];
  //   }, [nodes.Object_6.geometry]);

  //   const [ref, api] = useBox(() => ({ type: "Kinematic", args: [3.4, 1, 3.5], onCollide: (e) => pong(e.contact.impactVelocity) }))

  const onPress = useCallback(
    (event) => {
      if (event.code === "Space") {
        event.preventDefault();
        console.log(`pressed`);

        api.velocity.set(0, 6, 0);
      }
    },
    [api]
  );

  const [ref, api] = useBox(
    () => ({
      mass: 1,
      args: [4, 4, 4],
      type: "Dynamic",
      onCollide: (e) => {
        if (e.contact.bi.uuid === props.boxUuid) {
          props.setTouched(true);
        }
        // ping.currentTime = 0
        // ping.volume = clamp(velocity / 20, 0, 1)
        // ping.play()
        // if (velocity > 4) set((state) => ({ count: state.count + 1 }))
      },
    }),
    useRef(),
    [props.boxUuid]
  );

  useEffect(() => {
    window.addEventListener("keydown", onPress);
    return () => {
      console.log("listener removed");
      window.removeEventListener("keydown", onPress);
    };
  }, [api]);

  return (
    <primitive
      ref={ref}
      object={scene}
      scale={0.3}
      position={[0, 0, 0]}
      onClick={() => api.velocity.set(0, 6, 0)}
    />
  );
}
